# Special responses

The models analyzed in the first two parts of the book were (with very few exceptions) characterized by a response that was a real number defined on the whole real line. When the response was a strictly positive real number, it was possible to coerce it to a real number by taking its logarithm. In this part, we'll consider models with "special responses", i.e., responses that are not defined on the whole real line. We'll then encounter responses that are either real but defined only on a part of the real line, integers or categorical. 
Most of the time, the models described in this part will be estimated by maximum likelihood, which means that they are highly parametrical as the distribution law of the response should be completely specified.

A fundamental difference with the linear model is that the conditional expectation of the response is no longer a linear function of the covariates. More specifically, in the first two parts of the book, we used a linear index function: $\mu_n = \alpha + \beta ^ \top x_n = \gamma ^ \top z_n$ and we had $\mbox{E}(y \mid x_n) = \mu_n$. Therefore, $\beta_k = \frac{\partial \mbox{E}(y \mid x_n)}{\partial x_{nk}}$ so that the marginal effect of the k^th^ covariate was the corresponding coefficient. In the chapters of this part, we'll denote $\eta_n = \alpha + \beta ^ \top x_n = \gamma ^ \top z_n$ the linear index function and $\mu_n$ a function of interest which will be most of the time the conditional expectation of the response. The two variables are related in the following way: $\eta_n =g(\mu_n)$, where the $g$ function is called the **link**. Therefore, we now have: $\frac{\partial \mu_n}{\partial x_{nk}}=\beta_k \frac{\partial g ^ {-1}}{\partial \eta_n}(\eta_n)$ so that the marginal effect of the k^th^ covariate is now proportional (but not equal) to the corresponding coefficient.

@sec-binomial is devoted to binomial responses, i.e., responses that take only two values. @sec-tobit presents truncated responses, for which the real value of the variable is only observed in a certain range. Count responses, i.e., responses that take non-negative integer values are presented in @sec-count. Models that deal with duration responses are presented in @sec-duration. Finally, @sec-rum is devoted to random utility models for multinomial responses. 
